exclusions:
# This crashes Python on laptop. Most likely out of memory
  - parser: Brain
    dataset: Hdfs
    proportion: 1/1

datasets:
  Hadoop:
    filename: "/hadoop/"
    filename_pattern: "*.log"
    labels_file_name: "/hadoop/abnormal_label_accurate.txt"
    loader: "HadoopLoader"
    proportion: 1/1
    test_fraction: 0.5
    repeats: 3
    predict: seq
  Bgl:
    filename: "/bgl/BGL.log"
    loader: "BGLLoader"
    proportion: 1/10
    test_fraction: 0.95
    repeats: 3
    predict: event
  Hdfs:
    filename: "/hdfs/HDFS.log"
    labels_file_name: "/hdfs/anomaly_label.csv"
    loader: "HDFSLoader"
    proportion: 1/10
    test_fraction: 0.95
    repeats: 3
    predict: seq
#  Pro:
#    filename: "/profilence/*.txt"
#    loader: "ProLoader"
#  Nezha-TrainTicket:
#    filename: "/nezha/"
#    loader: "NezhaLoader"
#  Nezha-Shop:
#    filename: "/nezha/"
#    loader: "NezhaLoader"  
# Laptop does not have sufficient memory for supercomputers    
#  Tb:
#    filename: "/thunderbird/Thunderbird.log"
#    loader: "ThuSpiLibLoader"
#  Spirit:
#    filename: "/spirit/spirit2.log"
#    loader: "ThuSpiLibLoader"
#  Liberty:
#    filename: "/liberty/liberty2.log"
#    loader: "ThuSpiLibLoader"


algos:
  - name: s_LR
    call: train_LR
  - name: s_DT
    call: train_DT
  - name: s_RF
    call: train_RF
  - name: s_SVM
    call: train_LSVM
  - name: s_XGB
    call: train_XGB
  - name: u_Kmeans
    call: train_KMeans
  - name: u_IsolationForrest
    call: train_IsolationForest

parsers:
  - name: Tip
    call: parse_tip
    field: e_event_tip_id
  # - name: Iplom
  #   call: parse_iplom
  #   field: e_event_iplom_id
  - name: Drain
    call: parse_drain
    field: e_event_drain_id
  - name: Pliplom
    call: parse_pliplom
    field: e_event_pliplom_id
#  - name: AEL
#    call: parse_ael
#    field: e_event_ael_id
#  - name: Spell
#    call: parse_spell
#    field: e_event_spell_id
  - name: Brain
    call: parse_brain
    field: e_event_brain_id  

#  - name: Lenma
#    call: parse_lenma
#    field: e_event_lenma_id

