name: ll_no_tf
channels:
  - defaults
dependencies:
  - _libgcc_mutex>=0.1
  - _openmp_mutex>=5.1
  - _py-xgboost-mutex>=2.0
  - abseil-cpp>=20211102.0
  - arrow-cpp>=14.0.2
  - asttokens>=2.0.5
  - attrs>=23.1.0
  - aws-c-auth>=0.6.19
  - aws-c-cal>=0.5.20
  - aws-c-common>=0.8.5
  - aws-c-compression>=0.2.16
  - aws-c-event-stream>=0.2.15
  - aws-c-http>=0.6.25
  - aws-c-io>=0.13.10
  - aws-c-mqtt>=0.7.13
  - aws-c-s3>=0.1.51
  - aws-c-sdkutils>=0.1.6
  - aws-checksums>=0.1.13
  - aws-crt-cpp>=0.18.16
  - aws-sdk-cpp>=1.10.55
  - backcall>=0.2.0
  - blas>=1.0
  - boost-cpp>=1.82.0
  - bottleneck>=1.3.7
  - brotli>=1.0.9
  - brotli-bin>=1.0.9
  - brotli-python>=1.0.9
  - bzip2>=1.0.8
  - c-ares>=1.19.1
  - ca-certificates>=2024.3.11
  - certifi>=2024.2.2
  - charset-normalizer>=2.0.4
  - click>=8.1.7
  - cloudpickle>=2.2.1
  - comm>=0.2.1
  - contourpy>=1.2.0
  - curl>=8.7.1
  - cycler>=0.11.0
  - cyrus-sasl>=2.1.28
  - dbus>=1.13.18
  - debugpy>=1.6.7
  - decorator>=5.1.1
  - executing>=0.8.3
  - expat>=2.5.0
  - fontconfig>=2.14.1
  - fonttools>=4.25.0
  - freetype>=2.12.1
  - gdbm>=1.18
  - gettext>=0.21.0
  - gflags>=2.2.2
  - giflib>=5.2.1
  - git>=2.40.1
  - gitdb>=4.0.7
  - gitpython>=3.1.37
  - glib>=2.78.4
  - glib-tools>=2.78.4
  - glog>=0.5.0
  - grpc-cpp>=1.48.2
  - gst-plugins-base>=1.14.1
  - gstreamer>=1.14.1
  - icu>=73.1
  - idna>=3.7
  - intel-openmp>=2023.1.0
  - ipykernel>=6.28.0
  - ipython>=8.20.0
  - jedi>=0.18.1
  - jinja2>=3.1.3
  - joblib>=1.2.0
  - jpeg>=9e
  - jsonschema>=4.19.2
  - jsonschema-specifications>=2023.7.1
  - jupyter_client>=8.6.0
  - jupyter_core>=5.5.0
  - kiwisolver>=1.4.4
  - krb5>=1.20.1
  - lcms2>=2.12
  - ld_impl_linux-64>=2.38
  - lerc>=3.0
  - libboost>=1.82.0
  - libbrotlicommon>=1.0.9
  - libbrotlidec>=1.0.9
  - libbrotlienc>=1.0.9
  - libclang>=14.0.6
  - libclang13>=14.0.6
  - libcups>=2.4.2
  - libcurl>=8.5.0
  - libdeflate>=1.17
  - libedit>=3.1.20230828
  - libev>=4.33
  - libevent>=2.1.12
  - libffi>=3.4.4
  - libgcc-ng>=11.2.0
  - libgfortran-ng>=11.2.0
  - libgfortran5>=11.2.0
  - libglib>=2.78.4
  - libgomp>=11.2.0
  - libiconv>=1.16
  - libllvm14>=14.0.6
  - libnghttp2>=1.57.0
  - libpng>=1.6.39
  - libpq>=12.17
  - libprotobuf>=3.20.3
  - libsodium>=1.0.18
  - libssh2>=1.10.0
  - libstdcxx-ng>=11.2.0
  - libthrift>=0.15.0
  - libtiff>=4.5.1
  - libuuid>=1.41.5
  - libwebp>=1.3.2
  - libwebp-base>=1.3.2
  - libxcb>=1.15
  - libxgboost>=1.7.6
  - libxkbcommon>=1.0.1
  - libxml2>=2.10.4
  - llvmlite>=0.42.0
  - lz4-c>=1.9.4
  - markupsafe>=2.1.3
  - matplotlib>=3.8.0
  - matplotlib-base>=3.8.0
  - matplotlib-inline>=0.1.6
  - mkl>=2023.1.0
  - mkl-service>=2.4.0
  - mkl_fft>=1.3.8
  - mkl_random>=1.2.4
  - munkres>=1.1.4
  - mysql>=5.7.24
  - nbformat>=5.9.2
  - ncurses>=6.4
  - nest-asyncio>=1.6.0
  - numba>=0.59.1
  - numexpr>=2.8.7
  - numpy>=1.26.4
  - numpy-base>=1.26.4
  - openjpeg>=2.4.0
  - openssl>=3.0.13
  - orc>=1.7.4
  - packaging>=23.2
  - pandas>=2.2.1
  - parso>=0.8.3
  - pcre>=8.45
  - pcre2>=10.42
  - perl>=5.34.0
  - pexpect>=4.8.0
  - pickleshare>=0.7.5
  - pillow>=10.2.0
  - pip>=23.3.1
  - platformdirs>=3.10.0
  - plotly>=5.19.0
  - ply>=3.11
  - prompt-toolkit>=3.0.43
  - prompt_toolkit>=3.0.43
  - psutil>=5.9.0
  - ptyprocess>=0.7.0
  - pure_eval>=0.2.2
  - py-xgboost>=1.7.6
  - pyarrow>=14.0.2
   - pybind11-abi>=5
  - pygments>=2.15.1
  - pyparsing>=3.0.9
  - pyqt>=5.15.10
  - pyqt5-sip>=12.13.0
  - pysocks>=1.7.1
  - python>=3.11.5
  - python-dateutil>=2.8.2
  - python-dotenv>=0.21.0
  - python-fastjsonschema>=2.16.2
  - python-tzdata>=2023.3
  - pytz>=2023.3.post1
  - pyyaml>=6.0.1
  - pyzmq>=25.1.2
  - qt-main>=5.15.2
  - re2>=2022.04.01
  - readline>=8.2
  - referencing>=0.30.2
  - regex>=2023.10.3
  - requests>=2.32.2
  - rpds-py>=0.10.6
  - s2n>=1.3.27
  - scikit-learn>=1.2.2
  - scipy>=1.12.0
  - setuptools>=68.2.2
  - shap>=0.42.1
  - sip>=6.7.12
  - six>=1.16.0
  - slicer>=0.0.7
  - smmap>4.0.0
  - snappy>=1.1.10
  - sqlite>=3.41.2
  - stack_data>=0.2.0
  - tbb>=2021.8.0
  - tenacity>=8.2.2
  - threadpoolctl>=2.2.0
  - tk>=8.6.12
  - tornado>=6.3.3
  - tqdm>=4.65.0
  - traitlets>=5.7.1
  - tzdata>=2024a
  - unicodedata2>=15.1.0
  - urllib3>=2.2.1
  - utf8proc>=2.6.1
  - wcwidth>=0.2.5
  - wheel>=0.41.2
  - xgboost>=1.7.6
  - xz>=5.4.6
  - yaml>=0.2.5
  - zeromq>=4.3.5
  - zlib>=1.2.13
  - zstd>=1.5.5
  - pip:
    - cachetools>=4.2.1
    - drain3>=0.9.11
    - jsonpickle>=1.5.1
    - polars==0.20.21
    - pynndescent>=0.5.12
    - tipping>=0.1.3
    - umap-learn>=0.5.6
