# Config file for Hadoop data. Download it from:
# https://zenodo.org/records/8196385/files/Hadoop.zip?download=1 

# Specify input data and output folders
input_data_folder: "/home/mmantyla/Datasets/hadoop"
output_folder: "output_hadoop"

preprocessing_steps:
  - name: "remove_run_name_from_file_names"

steps:
  # Similarity based comparisons
  # Level 1
  distance_run_file:
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
   
  # Level 2
  distance_run_content:
    - target_run: "application_1445062781478_0011"
      comparison_runs:
        - "application_1445062781478_0012"
        - "application_1445062781478_0013"
        - "application_1445062781478_0014"
      normalize_content: False

  #Level 3
  distance_file_content:
    - target_run: "application_1445062781478_0011"
      comparison_runs:
        - "application_1445062781478_0012"
        - "application_1445062781478_0013"
        - "application_1445062781478_0014"
      normalize_content: True
    - target_run: "application_1445062781478_0011"
      comparison_runs:
        - "application_1445062781478_0012"
        - "application_1445062781478_0013"
        - "application_1445062781478_0014"
      normalize_content: False
  
  #Level 4
  distance_line_content:
    - target_run: "application_1445062781478_0011"
      target_files:
      - "container__01_000001.log"
      - "container__01_000002.log"
      - "container__01_000003.log"
      comparison_runs:
        - "application_1445062781478_0012"
        - "application_1445062781478_0013"
        - "application_1445062781478_0014"
      normalize_content: True

  # Anomaly detection based models
  # Level 1
  anomaly_run_file: 
    - target_run: 3 #for anomaly_run_file we can also specify a number for target_run
      comparison_runs: 10
      detectors:
        - IsolationForest
        - KMeans
        - RarityModel
        - OOVDetector
  # Level 2
  anomaly_run_content:
    - target_run: 3
      comparison_runs: 10 #for anomaly_run_file we can also specify a number for target_run
      normalize_content: True
      detectors:
        - IsolationForest
        - KMeans
        - RarityModel
        - OOVDetector

  # Level 3
  anomaly_file_content:
    - target_run: "application_1445062781478_0011"
      target_files:
      - "container__01_000001.log"
      - "container__01_000002.log"
      - "container__01_000003.log"
      comparison_runs: 10
      normalize_content: True
      detectors:
        - IsolationForest
        - KMeans
        - RarityModel
        - OOVDetector

  # Level 4 - includes plotting
  anomaly_line_content:
    - target_run: "application_1445062781478_0011"
      target_files:
      - "container__01_000001.log"
      - "container__01_000002.log"
      - "container__01_000003.log"
      comparison_runs: "ALL"
      normalize_content: True
      detectors:
       - IsolationForest
       - KMeans
       - RarityModel
       - OOVDetector
      content_format: "Words" #Valid options: 3grams, Parse, Sklearn
      vectorizer: "Tfidf" #Valid options: Count
  #Plotting. 
  #Level 1
  plot_run_file:
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      group_by_indices: [0, 1] #use first and second element WordCount and DiskFull

  #Level 1
  plot_run_content:
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      group_by_indices: [0, 1] 
      normalize_content: True
      content_format: "3grams"
      vectorizer: "Tfidf"
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      group_by_indices: [0, 1] 
      normalize_content: True
      content_format: "Words"
      vectorizer: "Count"
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      group_by_indices: [0, 1] 
      normalize_content: True
      content_format: "Parse"
      vectorizer: "Tfidf"
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      group_by_indices: [0, 1] 
      normalize_content: True
      content_format: "Sklearn"
      vectorizer: "Tfidf"
    
  #Level 3 - Same options as Level 2 plotting for vectorizer and content_format
  plot_file_content:
    - target_run: "application_1445062781478_0011"
      comparison_runs: "ALL"
      target_files:
      - "container__01_000001.log"
      group_by_indices: [0, 1]
      normalize_content: True
      content_format: "Words"
      vectorizer: "Tfidf"



